---
deployment:
  tasks:
    # IMPORTANT: Replace 'cpuser' with your actual cPanel username.
    # If your domain's document root is not public_html, adjust the path below.
    - export DEPLOYPATH=/home/cpuser/public_html/
    
    # 1. Install dependencies
    - npm install
    
    # 2. Build the Vite project
    - npm run build
    
    # 3. Copy the built files from the 'dist' folder to the public directory
    - /bin/cp -R dist/* $DEPLOYPATH
